author: mrmag518
description: "An assortment of beneficial features."
main: com.mrmag518.iSafe.iSafe
name: iSafe
load: STARTUP
version: 'Upcoming 3.0'
website: http://dev.bukkit.org/server-mods/blockthattnt/
softdepend: [Vault]
commands:
  iSafe:
    description: Main command for iSafe.
    usage: /<command>
permissions:
  iSafe.command.reload:
    default: op
  iSafe.command.info:
    default: op
  iSafe.command.serverinfo:
    default: op
  iSafe.enchant:
    default: op
    
  recreate all permission nodes, no worries I have backup ^^:
    default: false
    