author: mrmag518
description: "Configurable features related to events happening on the server."
main: me.mrmag518.iSafe.iSafe
name: iSafe
load: STARTUP 
version: '2.34'
website: http://dev.bukkit.org/server-mods/blockthattnt/
commands:
  iSafe-reload:
    description: Reload iSafe
    usage: "Usage: /<command>"
    aliases: [reloadiSafe, iSafereload]
  iSafe-info:
    description: Get information about iSafe
    usage: "Usage: /<command>"
    aliases: [infoisafe, isafeinfo]
  iSafe-commands:
    description: Get the commands for iSafe
    usage: "Usage: /<command>"
    aliases: [isafecommands, isafecmds, isafe-cmds]
  serverinfo:
    description: Get info about the server
    usage: "Usage: /<command>"
    aliases: [isafe-serverinfo, server-info, myserver]
  superbreak:
    description: Enable or Disable the superbreak feature.
    usage: "Usage: /<command>"
    aliases: [sb, instantbreak, superfits]
  healme:
    description: Heal yourself.
    usage: "Usage: /<command>"
    aliases: [meheal, iwanthealth]
permissions:
  iSafe.*:
    description: Allow the user to get access to all the iSafe permissions.
    default: op
    children:
      iSafe.serverinfo: true
      iSafe.drop: true
      iSafe.place.tnt: true
      iSafe.break.tnt: true
      iSafe.break.mobspawner: true
      iSafe.place.mobspawner: true
      iSafe.place.bedrock: true
      iSafe.place.fireblock: true
      iSafe.place.obsidian: true
      iSafe.break.obsidian: true
      iSafe.place.waterblock: true
      iSafe.place.lavablock: true
      iSafe.place.piston: true
      iSafe.lavabucket.empty: true
      iSafe.superstick: true
      iSafe.sprint: true
      iSafe.break.piston: true
      iSafe.sneak: true
      iSafe.break.sponge: true
      iSafe.place.sponge: true
      iSafe.place.ice: true
      iSafe.ice.break: true
      iSafe.reload: true
      iSafe.drop.tnt: true
      iSafe.drop.diamondblock: true
      iSafe.drop.ironblock: true
      iSafe.drop.goldblock: true
      iSafe.drop.diamondore: true
      iSafe.drop.bedrock: true
      iSafe.drop.un-natural-portal: true
      iSafe.drop.diamondingot: true
      iSafe.place.un-naturalportal: true
      iSafe.info: true
      iSafe.teleport: true
      iSafe.chat: true
      iSafe.bed-enter: true
      iSafe.place.soulsand: true
      iSafe.break.soulsand: true
      iSafe.commandlist: true
      iSafe.fish: true
      iSafe.interact.buttons: true
      iSafe.interact.woodendoors: true
      iSafe.interact.irondoors: true
      iSafe.interact.stonepressureplate: true
      iSafe.interact.woodenpressureplate: true
      iSafe.interact.levers: true
      iSafe.interact.trapdoor: true
      iSafe.interact.woodenfencegate: true
      iSafe.interact.chest: true
      iSafe.pickup: true
      iSafe.vehicle.enter.minecart: true
      iSafe.vehicle.enter.boat: true
      iSafe.vehicle.destory.minecart: true
      iSafe.vehicle.destory.boat: true
      iSafe.superbreak: true
      iSafe.heal: true
  iSafe.place.*:
    description: Allow the user to get access to all the Place permissions.
    default: op
    children:
      iSafe.place.tnt: true
      iSafe.place.mobspawner: true
      iSafe.place.bedrock: true
      iSafe.place.fireblock: true
      iSafe.place.obsidian: true
      iSafe.place.waterblock: true
      iSafe.place.lavablock: true
      iSafe.place.piston: true
      iSafe.place.sponge: true
      iSafe.place.ice: true
      iSafe.place.un-naturalportal: true
      iSafe.place.soulsand: true
  iSafe.break.*:
    desccription: Allow the user to get all the access to Break permissions.
    default: op
    children:
      iSafe.break.tnt: true
      iSafe.break.mobspawner: true
      iSafe.break.obsidian: true
      iSafe.break.piston: true
      iSafe.break.sponge: true
      iSafe.break.ice: true
      iSafe.break.soulsand: true
  iSafe.drop.*:
    description: Allow the user to get all access tothe Drop permissions.
    default: op
    children:
      iSafe.drop: true
      iSafe.drop.tnt: true
      iSafe.drop.diamondblock: true
      iSafe.drop.ironblock: true
      iSafe.drop.goldblock: true
      iSafe.drop.diamondore: true
      iSafe.drop.bedrock: true
      iSafe.drop.un-natural-portal: true
      iSafe.drop.diamondingot: true
  iSafe.interact.*:
    description: Allow the user to get access to all the Interact permissions.
    default: op
    children:
      iSafe.interact.buttons: true
      iSafe.interact.woodendoors: true
      iSafe.interact.irondoors: true
      iSafe.interact.stonepressureplate: true
      iSafe.interact.woodenpressureplate: true
      iSafe.interact.levers: true
      iSafe.interact.trapdoor: true
      iSafe.interact.woodenfencegate: true
      iSafe.interact.chest: true
  iSafe.vehicle.*:
    description: Allow the user to get access to all the Vehicle permissions.
    default: op
    childred:
      iSafe.vehicle.enter.minecart: true
      iSafe.vehicle.enter.boat: true
      iSafe.vehicle.destory.minecart: true
      iSafe.vehicle.destory.boat: true
  iSafe.place.tnt:
    default: op
  iSafe.break.tnt:
    default: op
  iSafe.break.mobspawner:
    default: op
  iSafe.place.mobspawner:
    default: op
  iSafe.place.bedrock:
    default: op
  iSafe.place.fireblock:
    default: op
  iSafe.place.obsidian:
    default: op
  iSafe.break.obsidian:
    default: op
  iSafe.place.waterblock:
    default: op
  iSafe.place.lavablock:
    default: op
  iSafe.place.piston:
    default: op
  iSafe.lavabucket.empty:
    default: op
  iSafe.superstick:
    default: op
  iSafe.sprint:
    default: op
  iSafe.break.piston:
    default: op
  iSafe.sneak:
    default: op
  iSafe.break.sponge:  
    default: op
  iSafe.place.sponge:
    default: op
  iSafe.place.ice:
    default: op
  iSafe.break.ice:
    default: op
  iSafe.waterbucket.empty:
    default: op
  iSafe.reload:
    default: op
  iSafe.drop.tnt:
    default: op
  iSafe.drop.diamondblock:
    default: op
  iSafe.drop.ironblock:
    default: op
  iSafe.drop.goldblock:
    default: op
  iSafe.drop.diamondore:
    default: op
  iSafe.drop.bedrock:
    default: op
  iSafe.drop.un-natural-portal:
    default: op
  iSafe.drop.diamondingot:
    default: op
  iSafe.place.un-naturalportal:
    default: op
  iSafe.info:
    default: op
  iSafe.teleport:
    default: op
  iSafe.chat:
    default: op
  iSafe.bed-enter:
    default: op
  iSafe.place.soulsand:
    default: op
  iSafe.break.soulsand:
    default: op
  iSafe.commandlist:
    default: op
  iSafe.fish:
    default: op
  iSafe.interact.buttons:
    default: op
  iSafe.interact.woodendoors:
    default: op
  iSafe.interact.irondoors:
    default: op
  iSafe.interact.stonepressureplate:
    default: op
  iSafe.interact.woodenpressureplate:
    default: op
  iSafe.interact.levers:
    default: op
  iSafe.interact.trapdoor:
    default: op
  iSafe.interact.woodenfencegate:
    default: op
  iSafe.interact.chest:
    default: op
  iSafe.drop:
    default: op
  iSafe.serverinfo:
    default: op
  iSafe.pickup:
    default: op
  iSafe.superbreak:
    default: op
  iSafe.heal:
    default: op